const SUPABASE_URL = 'https://qmslmhoxpzqdxuucwxtu.supabase.co';
const SUPABASE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFtc2xtaG94cHpxZHh1dWN3eHR1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODYzNDkxODUsImV4cCI6MjEwMTkyNTE4NX0.lyF5U_p1pIF8dK_rJ73dKZeZWrJ8fANIjmDultLATqo';
const supabaseClient = supabase.createClient(SUPABASE_URL, SUPABASE_KEY);
